version: '3.8'

services:
  yt-dlp-web-gui:
    image: toastbrotlf2000/yt-dlp-web-gui:latest


    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./downloads:/app/downloads
    restart: unless-stopped
